apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rlgw.fullname" . }}
  labels: {{- include "rlgw.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
