apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rlgw.fullname" . }}
  labels: {{- include "rlgw.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels: {{- include "rlgw.selectorLabels" . | nindent 6 }}
